
-- USER is a reserved keyword with Postgres
-- You must use double quotes in every query that user is in:
-- ex. SELECT * FROM "user";
-- Otherwise you will have errors!

-- Table Creation queries -- 
CREATE TABLE "user" (
	"id" serial NOT NULL PRIMARY KEY,
	"username" varchar(25) NOT NULL,
	"password" varchar(250) NOT NULL,
	"first_name" varchar(25) NOT NULL,
	"last_name" varchar(25) NOT NULL,
	"is_doctor" BOOLEAN NOT NULL DEFAULT 'FALSE'
);

CREATE TABLE "patients" (
	"id" serial NOT NULL PRIMARY KEY,
	"first_name" VARCHAR(255) NOT NULL,
	"last_name" VARCHAR(255) NOT NULL,
	"has_treatment_plan" BOOLEAN NOT NULL DEFAULT 'FALSE'
);

CREATE TABLE "muscle_work_bank" (
	"id" serial NOT NULL PRIMARY KEY,
	"muscle_work_name" VARCHAR(255) NOT NULL,
	"muscle_work_type" VARCHAR(255) NOT NULL
);

CREATE TABLE "exercise_bank" (
	"id" serial NOT NULL PRIMARY KEY,
	"exercise_name" TEXT NOT NULL
);

CREATE TABLE "exercise_variations" (
	"id" serial NOT NULL PRIMARY KEY,
	"exercise_id" integer NOT NULL REFERENCES "exercise_bank"("id"),
	"exercise_variation" TEXT
);

CREATE TABLE "treatment_plans" (
	"id" serial NOT NULL PRIMARY KEY,
	"patient_id" integer NOT NULL REFERENCES "patients"("id"),
	"visit_count" integer NOT NULL,
	"primary_complaint_area" TEXT NOT NULL,
	"primary_exercise_focus" TEXT NOT NULL,
	"secondary_exercise_focus" TEXT NOT NULL,
	"notes_for_rehab" TEXT,
	"units" integer NOT NULL
);

CREATE TABLE "visit_information" (
	"id" serial NOT NULL PRIMARY KEY,
	"date" DATE,
	"time_in" TIME,
	"time_out" TIME,
	"total_time" integer,
	"therapist" integer NOT NULL REFERENCES "user"("id"),
	"units_completed" integer,
	"treatment_plan_id" integer NOT NULL REFERENCES "treatment_plans"("id")
);

CREATE TABLE "muscle_work_to_be_done" (
	"id" serial NOT NULL PRIMARY KEY,
	"muscle_work_id" integer NOT NULL REFERENCES "muscle_work_bank"("id"),
	"treatment_plan_id" integer NOT NULL REFERENCES "treatment_plans"("id")
);

CREATE TABLE "all_exercises_done" (
	"id" serial NOT NULL PRIMARY KEY,
	"exercise_id" integer NOT NULL REFERENCES "exercise_bank"("id"),
	"variation_id" integer NOT NULL REFERENCES "exercise_variations"("id"),
	"sets_done" integer,
	"reps_done" integer,
	"notes_for_exercise" TEXT, 
	"visit_information_id" integer NOT NULL REFERENCES "visit_information"("id")
);

CREATE TABLE "muscle_work_to_be_done_per_visit" (
	"id" serial NOT NULL PRIMARY KEY,
	"muscle_work_to_be_done_id" integer NOT NULL REFERENCES "muscle_work_to_be_done"("id"),
	"visit_information_id" integer NOT NULL REFERENCES "visit_information"("id"),
	"is_done" BOOLEAN NOT NULL DEFAULT FALSE
);

-- Insert Muscle Work, exercises and exercise variations to be chosen from --
INSERT INTO "muscle_work_bank" ("muscle_work_name", "muscle_work_type")
VALUES 
('C/S Paraspinals', 'Prone AMR via Graston'),
('C/S Paraspinals', 'Seated AMR via Graston'),
('C/S Paraspinals', 'Prone AMR by Hand'),
('T/S Paraspinals', 'Prone AMR via Graston'),
('T/S Paraspinals', 'Seated AMR via Graston'),
('T/S Paraspinals', 'Seated AMR by Hand'),
('L/S Paraspinals', 'Prone AMR via Graston'),
('L/S Paraspinals', 'Seated AMR via Graston'),
('L/S Paraspinals', 'Seated AMR by Hand'),
('Upper Trap', 'Seated AMR via Graston'),
('Upper Trap', 'Seated AMR by Hand'),
('Upper Trap', 'PNF'),
('Levator Scap', 'Seated AMR via Graston'),
('Levator Scap', 'Seated AMR by Hand'),
('Levator Scap', 'PNF'),
('Rhomboid', 'Prone AMR via Graston'),
('Rhomboid', 'Prone AMR by Hand'),
('Pec Major', 'AMR by Hand'),
('Pec Major', 'AMR via Graston'),
('Pec Minor', 'AMR by Hand'),
('Pec Minor', 'AMR via Graston'),
('Pec Major', 'PNF'),
('Pec Minor', 'PNF'),
('Temporalis', 'AMR by Hand'),
('Temporalis', 'AMR via Graston'),
('Masseter', 'AMR by Hand'),
('Masseter', 'AMR via Graston'),
('SOT', 'AMR by Hand'),
('SOT', 'AMR via Graston'),
('SOT', 'PNF'),
('Scalenes', 'AMR by Hand'),
('Scalenes', 'AMR via Graston'),
('SCM', 'AMR by Hand'),
('SCM', 'AMR via Graston'),
('Pterygoids', 'External AMR'),
('Pterygoids', 'Internal AMR'),
('QL', 'Seated AMR via Graston'),
('QL', 'Seated AMR by Hand'),
('QL', 'Prone AMR via Graston'),
('Glute', 'AMR via Hand/Elbow'),
('Piriformis', 'AMR via Hand/Elbow'),
('Glute/Piriformis', 'PNF'),
('TFL', 'AMR by Hand/Elbow'),
('TFL', 'AMR via Stick'),
('Iliopsoas', 'AMR by Hand'),
('Iliopsoas', 'PNF'),
('Hamstring', 'AMR via Stick'),
('Hamstring', 'AMR via Graston'),
('Hamstring', 'AMR by Hand/Elbow'),
('Hamstring', 'PNF'),
('Adductor', 'AMR via Stick'),
('Adductor', 'AMR via Graston'),
('Adductor', 'AMR by Hand'),
('IT Band', 'AMR via Stick'),
('IT Band', 'AMR via Graston'),
('IT Band', 'AMR by Hand'),
('Gastro/Soleus', 'AMR via Stick'),
('Gastro/Soleus', 'AMR via Graston'),
('Gastro/Soleus', 'AMR by Hand'),
('Gastro/Soleus', 'PNF');

INSERT INTO "exercise_bank" ("exercise_name")
VALUES ('Lumbar Extension'),
('Prone Hip Extension'),
('Prone Press Up'),
('Glute Set'),
('Transverse Abdominus Set'),
('Floor Bridge'),
('Pelvic Tilt'),
('Deadbug'),
('Butterfly Bridge'),
('Theraball Bridge on Table'),
('Theraball Trunk Extension'),
('Theraball Wall Squat'),
('Prone Plank'),
('Lunge'),
('Tube Torso Stability'),
('Single Leg Balance'),
('Single Leg Kneel'),
('Clamshell'),
('Side Lying Hip ABDuction'),
('Side Lying Hip ADDuction'),
('Cervical Isometric Series'),
('Cervical Retraction'),
('Cervical Isometric Extension'),
('Chin Tuck and Hold'),
('Chin Tuck and Lift'),
('Scapular Retraction'),
('Scapular Depression'),
('Theraball Ab Set'),
('Wall Angels'),
('Quadraped'),
('Theraband Pulldown'),
('Theraband Row'),
('Theraball Prone Roller Rockout'),
('Theraball Swim'),
('Theraball Superman'),
('Foam Roller Pelvic Tilt'),
('Foam Roller Fly'),
('Theraball Bridge on Floor'), 
('Internal Woodchop'),
('External Woodchop'),
('YWTLs'),
('Bent Over T-Rotation'),
('Serratus Wall Slide'),
('Supine Pullover'),
('Band External Rotation');

INSERT INTO "exercise_variations" ("exercise_id", "exercise_variation")
VALUES (1 ,'3 second hold'),
(1, '5 second hold'),
(1, '8 second hold'),
(1, '10 second hold'),
(1, 'with scapular retraction'),
(2, 'with arms'),
(3, 'using arm rests'),
(4 ,'3 second hold'),
(4, '5 second hold'),
(4, '8 second hold'),
(4, '10 second hold'),
(5 ,'3 second hold'),
(5, '5 second hold'),
(5, '8 second hold'),
(5, '10 second hold'),
(6, 'Lvl 1'),
(6, 'Lvl 1 with arms'),
(6, 'Lvl 2'),
(6, 'Lvl 3'),
(6, 'single leg using left'),
(6, 'single leg using right'),
(6, 'single leg using left with arms'),
(6, 'single leg using right with arms'),
(7, 'Lvl 1'),
(7, 'Lvl 1 with arms'),
(7, 'Lvl 2'),
(7, 'Lvl 2 with arms'),
(7, 'Lvl 3'),
(8, 'Lvl 1'),
(8, 'Lvl 1 with arms'),
(8, 'Lvl 2 with static arms'),
(8, 'Lvl 3'),
(9, 'with arms'),
(9, 'without arms'),
(10, 'Lvl 1'),
(10, 'Lvl 1 with heel roll'),
(10, 'Lvl 2'),
(10, 'Lvl 2 with heel roll'),
(11, 'Arms at chest'),
(11, 'Arms extended'),
(11, 'Arms extended with 1lb dumbbells'),
(11, 'Arms extended with 2lbs dumbbells'),
(11, 'Arms extended with 3lbs dumbbells'),
(11, 'Arms extended with 5lbs dumbbells'),
(12, 'Half depth'),
(12, 'Full depth'),
(12, 'Band around knees'),
(12, 'Single leg'),
(12, 'Pulse x1'),
(12, 'Pulse x2'),
(12, 'Pulse x3'),
(13, 'On elbows and toes'),
(13, 'On elbows and knees'),
(13, '10 second hold'),
(13, '20 second hold'),
(13, '30 second hold'),
(13, '45 second hold'),
(13, '60 second hold'),
(13, '90 second hold'),
(14, 'Static'),
(14, 'Dynamic'),
(14, 'Backward'),
(14, 'Pulse'),
(14, 'Eyes-closed'),
(14, 'Perturbations'),
(15, 'with yellow bands'),
(15, 'with red bands'),
(15, 'with green bands'),
(15, 'with blue wobbles'),
(15, 'with black wobbles'),
(15, 'with blue circle wobbles'),
(16, '10 second hold'),
(16, '20 second hold'),
(16, '30 second hold'),
(16, '45 second hold'),
(16, '60 second hold'),
(16, '90 second hold'),
(16, 'ABC pattern'),
(16, 'Star pattern'),
(16, 'Eyes closed'),
(16, 'with green wobble'),
(16, 'with blue wobble'),
(16, 'with black wobble'),
(16, 'with blue circle wobble'),
(16, 'with perturbations'),
(17, '10 second hold'),
(17, '20 second hold'),
(17, '30 second hold'),
(17, '45 second hold'),
(17, '60 second hold'),
(17, '90 second hold'),
(17, 'Eyes closed'),
(17, 'Back foot up'),
(17, 'with perturbations'),
(18, 'Lvl 1'),
(18, 'Lvl 1 with band around knees'),
(18, 'Lvl 2'),
(18, 'Lvl 2 with band around knees'),
(18, 'Lvl 3'),
(19, 'with band around ankle'),
(19, 'Pulse'),
(20, 'with band around ankle'),
(20, 'Pulse'),
(21, '3 second hold'),
(21, '5 second hold'),
(21, '8 second hold'),
(21, '10 second hold'),
(22, 'Prone'),
(22, 'Seated'),
(23, '3 second hold'),
(23, '5 second hold'),
(23, '8 second hold'),
(23, '10 second hold'),
(23, '15 second hold'),
(23, '20 second hold'),
(24, '3 second hold'),
(24, '5 second hold'),
(24, '8 second hold'),
(24, '10 second hold'),
(25, '1 at time'),
(25, '2 at time'),
(25, '3 at time'),
(25, '4 at time'),
(25, '5 at time'),
(25, '6 at time'),
(25, '7 at time'),
(25, '8 at time'),
(26, '3 second hold'),
(26, '5 second hold'),
(26, '10 second hold'),
(27, '3 second hold'),
(27, '5 second hold'),
(27, '10 second hold'),
(28, '3 second hold'),
(28, '5 second hold'),
(28, '10 second hold'),
(29, '10 second hold'),
(29, '15 second hold'),
(29, '20 second hold'),
(29, '30 second hold'),
(29, '45 second hold'),
(29, '60 second hold'),
(29, '90 second hold'),
(30, 'Feet up'),
(30, 'with body blode'),
(30, 'with theraball'),
(30, 'with green wobbles'),
(30, 'with blue wobbles'),
(30, 'with black wobbles'),
(30, 'with blue circle wobbles'),
(31, 'on theraball with yellow bands'),
(31, 'on theraball with red bands'),
(31, 'on theraball with green bands'),
(31, 'Standing with yellow bands'),
(31, 'Standing with red bands'),
(31, 'Standing with green bands'),
(32, 'on theraball with yellow bands'),
(32, 'on theraball with red bands'),
(32, 'on theraball with green bands'),
(32, 'Standing with yellow bands'),
(32, 'Standing with red bands'),
(32, 'Standing with green bands'),
(33, 'Single leg'),
(34, 'Single leg'),
(35, 'Single leg'),
(35, 'with scapular retraction'),
(36, 'Lvl 1'),
(36, 'Lvl 1 with arms'),
(36, 'Lvl 2'),
(36, 'Lvl 3'),
(37, 'Bodyweight'),
(37, 'with 1lb dumbbells'),
(37, 'with 2lbs dumbbells'),
(37, 'with 3lbs dumbbells'),
(37, 'with 5lbs dumbbells'),
(38, 'Bodyweight'),
(38, 'with 1lb dumbbells'),
(38, 'with 2lbs dumbbells'),
(38, 'with 3lbs dumbbells'),
(38, 'with 5lbs dumbbells'),
(39, 'with yellow bands'),
(39, 'with red bands'),
(39, 'with green bands'),
(40, 'with yellow bands'),
(40, 'with red bands'),
(40, 'with green bands'),
(41, '3 second holds'),
(41, '5 second holds'),
(41, '8 second holds'),
(41, '10 second holds'),
(42, 'External bodyweight'),
(42, 'Internal bodyweight'),
(42, 'External 1lb dumbbells'),
(42, 'Internal 1lb dumbbells'),
(42, 'External 2lbs dumbbells'),
(42, 'Internal 2lbs dumbbells'),
(42, 'External 3lbs dumbbells'),
(42, 'Internal 3lbs dumbbells'),
(42, 'External 5lbs dumbbells'),
(42, 'Internal 5lbs dumbbells'),
(43, 'using foam roller'),
(43, 'flat against wall'),
(43, 'using yellow bands'),
(43, 'using red bands'),
(43, 'using green bands'),
(44, 'Bodyweight'),
(44, 'Bodyweight with lacrosse balls'),
(44, '1lb dumbbells'),
(44, '1lb dumbbells with lacrosse balls'),
(44, '2lbs dumbbells'),
(44, '2lbs dumbbells with lacrosse balls'),
(44, '3lbs dumbbells'),
(44, '3lbs dumbbells with lacrosse balls'),
(44, '5lbs dumbbells'),
(44, '5lbs dumbbells with lacrosse balls'),
(45, 'using red band'),
(45, 'using green band');
